const canvas = d3.select(".canva");
const svg = canvas.append("svg")
                .attr('width', "800")
                .attr('height', "250")

svg.append("circle")
    .attr("cx", "100")
    .attr("cy", "100")
    .attr("r", 50)
    .attr("fill", "blue")

svg.append("rect")
    .attr("width", "100")
    .attr("height", "100")
    .attr("fill", "orange")
    .attr("x", 150)
    .attr("y", 150)
    .attr("rx", 15)
    .attr("rx", 15)

svg.append("line")
    .attr("x1", 125)
    .attr("x2", 45)
    .attr("y1", 300)
    .attr("y2", 50)
    .attr("stroke", "red")

svg.append("text")
    .text("Hello")
    .attr("x", 150)
    .attr("y", 120)
    .attr("fill", "grey")
    .attr("font-size", 12)

svg.append("text")
    .text("There")
    .attr("x", 150)
    .attr("y", 140)
    .attr("fill", "grey")
    .attr("font-size", 12)

svg.append("text")
    .text("John")
    .attr("x", 150)
    .attr("y", 160)
    .attr("fill", "grey")
    .attr("font-size", 12)